spring.application.name=merchant
server.port = 8080

spring.datasource.url=jdbc:postgresql://localhost:5432/merchant_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000


logging.level.root=INFO
logging.level.com.alacriti=DEBUG

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration